// Mock data cho PickleballSports Community

export const tournaments = [
  {
    id: 1,
    name: "Giải Vô Địch Pickleball TP.HCM 2024",
    nameEn: "Ho Chi Minh City Pickleball Championship 2024",
    location: "Sân Pickleball Công viên Tao Đàn, TP.HCM",
    locationEn: "Tao Dan Park Pickleball Court, HCMC",
    date: "15-17/03/2024",
    status: "completed",
    participants: 48,
    prize: "50.000.000 VNĐ",
    image: "https://i.pinimg.com/736x/30/6d/44/306d441b00720a0479506c9bfe57e303.jpg",
    category: "Chuyên nghiệp",
    categoryEn: "Professional"
  },
  {
    id: 2,
    name: "Giải Pickleball Mở Rộng Hà Nội",
    nameEn: "Hanoi Open Pickleball Tournament",
    location: "Sân Pickleball Hồ Tây, Hà Nội",
    locationEn: "West Lake Pickleball Court, Hanoi",
    date: "20-22/04/2024",
    status: "upcoming",
    participants: 64,
    prize: "70.000.000 VNĐ",
    image: "https://i.pinimg.com/736x/30/6d/44/306d441b00720a0479506c9bfe57e303.jpg",
    category: "Mở rộng",
    categoryEn: "Open"
  },
  {
    id: 3,
    name: "Giải Pickleball Đà Nẵng Beach Cup",
    nameEn: "Da Nang Beach Pickleball Cup",
    location: "Bãi biển Mỹ Khê, Đà Nẵng",
    locationEn: "My Khe Beach, Da Nang",
    date: "10-12/05/2024",
    status: "upcoming",
    participants: 32,
    prize: "30.000.000 VNĐ",
    image: "https://i.pinimg.com/736x/30/6d/44/306d441b00720a0479506c9bfe57e303.jpg",
    category: "Giải trẻ",
    categoryEn: "Youth"
  },
  {
    id: 4,
    name: "Cúp Quốc Gia Pickleball 2024",
    nameEn: "National Pickleball Cup 2024",
    location: "Trung tâm Thể thao Quốc gia Mỹ Đình, Hà Nội",
    locationEn: "My Dinh National Sports Center, Hanoi",
    date: "01-05/06/2024",
    status: "registration",
    participants: 128,
    prize: "200.000.000 VNĐ",
    image: "https://i.pinimg.com/736x/30/6d/44/306d441b00720a0479506c9bfe57e303.jpg",
    category: "Quốc gia",
    categoryEn: "National"
  },
  {
    id: 5,
    name: "Giải Pickleball Cần Thơ Charity",
    nameEn: "Can Tho Pickleball Charity Tournament",
    location: "Công viên Lưu Hữu Phước, Cần Thơ",
    locationEn: "Luu Huu Phuoc Park, Can Tho",
    date: "15-16/07/2024",
    status: "registration",
    participants: 40,
    prize: "25.000.000 VNĐ",
    image: "https://i.pinimg.com/736x/30/6d/44/306d441b00720a0479506c9bfe57e303.jpg",
    category: "Thiện nguyện",
    categoryEn: "Charity"
  },
  {
    id: 6,
    name: "Giải Pickleball Đồng Đội Miền Nam",
    nameEn: "Southern Team Pickleball Championship",
    location: "Sân vận động Thống Nhất, TP.HCM",
    locationEn: "Thong Nhat Stadium, HCMC",
    date: "20-25/08/2024",
    status: "upcoming",
    participants: 80,
    prize: "100.000.000 VNĐ",
    image: "https://i.pinimg.com/736x/30/6d/44/306d441b00720a0479506c9bfe57e303.jpg",
    category: "Đồng đội",
    categoryEn: "Team"
  }
];

export const players = [
  { id: 1, rank: 1, name: "Nguyễn Văn An", province: "TP. Hồ Chí Minh", points: 2850, tournaments: 12, wins: 8 },
  { id: 2, rank: 2, name: "Trần Thị Bình", province: "Hà Nội", points: 2720, tournaments: 14, wins: 9 },
  { id: 3, rank: 3, name: "Lê Hoàng Cường", province: "Đà Nẵng", points: 2650, tournaments: 11, wins: 7 },
  { id: 4, rank: 4, name: "Phạm Thu Dung", province: "Cần Thơ", points: 2580, tournaments: 13, wins: 8 },
  { id: 5, rank: 5, name: "Võ Minh Đức", province: "TP. Hồ Chí Minh", points: 2510, tournaments: 10, wins: 6 },
  { id: 6, rank: 6, name: "Đặng Kim Oanh", province: "Hà Nội", points: 2480, tournaments: 12, wins: 7 },
  { id: 7, rank: 7, name: "Hoàng Văn Phúc", province: "Đà Nẵng", points: 2420, tournaments: 11, wins: 6 },
  { id: 8, rank: 8, name: "Ngô Thị Quỳnh", province: "Hải Phòng", points: 2380, tournaments: 9, wins: 5 },
  { id: 9, rank: 9, name: "Bùi Thanh Sang", province: "TP. Hồ Chí Minh", points: 2340, tournaments: 10, wins: 6 },
  { id: 10, rank: 10, name: "Trương Thị Tâm", province: "Cần Thơ", points: 2290, tournaments: 11, wins: 5 },
  { id: 11, rank: 11, name: "Lý Văn Toàn", province: "Hà Nội", points: 2240, tournaments: 8, wins: 4 },
  { id: 12, rank: 12, name: "Phan Thị Uyên", province: "Đà Nẵng", points: 2190, tournaments: 9, wins: 5 },
  { id: 13, rank: 13, name: "Đinh Văn Vũ", province: "Bình Dương", points: 2150, tournaments: 10, wins: 4 },
  { id: 14, rank: 14, name: "Mai Thị Xuân", province: "TP. Hồ Chí Minh", points: 2110, tournaments: 7, wins: 3 },
  { id: 15, rank: 15, name: "Dương Văn Yên", province: "Hà Nội", points: 2080, tournaments: 8, wins: 4 },
  { id: 16, rank: 16, name: "Hồ Thị Anh", province: "Huế", points: 2040, tournaments: 9, wins: 3 },
  { id: 17, rank: 17, name: "Vũ Văn Bảo", province: "Đà Nẵng", points: 2000, tournaments: 7, wins: 3 },
  { id: 18, rank: 18, name: "Chu Thị Chi", province: "Cần Thơ", points: 1960, tournaments: 8, wins: 2 },
  { id: 19, rank: 19, name: "Lưu Văn Đạt", province: "TP. Hồ Chí Minh", points: 1920, tournaments: 6, wins: 2 },
  { id: 20, rank: 20, name: "Đỗ Thị Em", province: "Hà Nội", points: 1880, tournaments: 7, wins: 2 }
];

export const news = [
  {
    id: 1,
    title: "Giải Vô Địch Pickleball TP.HCM 2024 Kết Thúc Thành Công",
    titleEn: "HCMC Pickleball Championship 2024 Concludes Successfully",
    excerpt: "Giải đấu quy tụ 48 vận động viên hàng đầu từ khắp cả nước đã khép lại với nhiều màn thi đấu hấp dẫn.",
    excerptEn: "The tournament gathered 48 top athletes from across the country and concluded with many exciting matches.",
    content: "Giải Vô Địch Pickleball TP.HCM 2024 đã khép lại với thành công rực rỡ...",
    date: "2024-03-18",
    category: "Giải đấu",
    categoryEn: "Tournament",
    image: "https://i.pinimg.com/736x/30/6d/44/306d441b00720a0479506c9bfe57e303.jpg",
    author: "Ban Biên Tập"
  },
  {
    id: 2,
    title: "Nguyễn Văn An Giữ Vững Ngôi Đầu Bảng Xếp Hạng Quốc Gia",
    titleEn: "Nguyen Van An Maintains Top National Ranking",
    excerpt: "Với chiến thắng ấn tượng tại giải đấu vừa qua, Nguyễn Văn An tiếp tục dẫn đầu bảng xếp hạng.",
    excerptEn: "With an impressive victory at the recent tournament, Nguyen Van An continues to lead the rankings.",
    content: "Nguyễn Văn An từ TP.HCM đã có một mùa giải xuất sắc...",
    date: "2024-03-15",
    category: "Vận động viên",
    categoryEn: "Athletes",
    image: "https://i.pinimg.com/736x/30/6d/44/306d441b00720a0479506c9bfe57e303.jpg",
    author: "Nguyễn Minh"
  },
  {
    id: 3,
    title: "Khai Mạc Giải Pickleball Mở Rộng Hà Nội - 64 Đội Tham Dự",
    titleEn: "Hanoi Open Pickleball Tournament Opens - 64 Teams Participating",
    excerpt: "Giải đấu mở rộng lớn nhất miền Bắc chính thức khai mạc với sự tham gia của 64 đội đến từ 15 tỉnh thành.",
    excerptEn: "The largest open tournament in Northern Vietnam officially opens with 64 teams from 15 provinces.",
    content: "Sáng ngày 20/04, tại Sân Pickleball Hồ Tây, Giải Pickleball Mở Rộng Hà Nội đã chính thức khai mạc...",
    date: "2024-03-12",
    category: "Sự kiện",
    categoryEn: "Events",
    image: "https://i.pinimg.com/736x/30/6d/44/306d441b00720a0479506c9bfe57e303.jpg",
    author: "Trần Hà"
  },
  {
    id: 4,
    title: "Hướng Dẫn Kỹ Thuật Pickleball Cơ Bản Cho Người Mới",
    titleEn: "Basic Pickleball Technique Guide for Beginners",
    excerpt: "Tìm hiểu kỹ thuật Pickleball - một trong những kỹ năng quan trọng nhất trong Pickleball.",
    excerptEn: "Learn about Pickleball technique - one of the most important skills in Pickleball.",
    content: "Kỹ thuật là nền tảng của môn Pickleball...",
    date: "2024-03-10",
    category: "Hướng dẫn",
    categoryEn: "Tutorial",
    image: "https://i.pinimg.com/736x/30/6d/44/306d441b00720a0479506c9bfe57e303.jpg",
    author: "HLV Lê Tuấn"
  },
  {
    id: 5,
    title: "Đà Nẵng Chuẩn Bị Cho Beach Pickleball Cup 2024",
    titleEn: "Da Nang Prepares for Beach Pickleball Cup 2024",
    excerpt: "Giải đấu độc đáo trên bãi biển Mỹ Khê hứa hẹn mang đến trải nghiệm mới mẻ cho các VĐV.",
    excerptEn: "The unique beach tournament at My Khe promises a new experience for athletes.",
    content: "Giải Beach Pickleball Cup tại Đà Nẵng sẽ là giải đấu đầu tiên được tổ chức trên bãi biển...",
    date: "2024-03-08",
    category: "Sự kiện",
    categoryEn: "Events",
    image: "https://i.pinimg.com/736x/30/6d/44/306d441b00720a0479506c9bfe57e303.jpg",
    author: "Phạm Lan"
  },
  {
    id: 6,
    title: "Trần Thị Bình: Hành Trình Từ Nghiệp Dư Đến Chuyên Nghiệp",
    titleEn: "Tran Thi Binh: Journey from Amateur to Professional",
    excerpt: "Câu chuyện truyền cảm hứng của VĐV nữ xuất sắc nhất Hà Nội.",
    excerptEn: "The inspiring story of Hanoi's most outstanding female athlete.",
    content: "Trần Thị Bình bắt đầu chơi Pickleball từ năm 2019...",
    date: "2024-03-05",
    category: "Vận động viên",
    categoryEn: "Athletes",
    image: "https://i.pinimg.com/736x/30/6d/44/306d441b00720a0479506c9bfe57e303.jpg",
    author: "Vũ Hương"
  },
  {
    id: 7,
    title: "Cúp Quốc Gia 2024: Mở Cổng Đăng Ký Từ 01/04",
    titleEn: "National Cup 2024: Registration Opens April 1st",
    excerpt: "Giải đấu lớn nhất năm với tổng giá trị giải thưởng 200 triệu đồng.",
    excerptEn: "The biggest tournament of the year with a total prize pool of 200 million VND.",
    content: "Ban Tổ Chức thông báo mở cổng đăng ký tham dự Cúp Quốc Gia Pickleball 2024...",
    date: "2024-03-03",
    category: "Thông báo",
    categoryEn: "Announcement",
    image: "https://i.pinimg.com/736x/30/6d/44/306d441b00720a0479506c9bfe57e303.jpg",
    author: "Ban Tổ Chức"
  },
  {
    id: 8,
    title: "Kỹ Thuật Shooting: Bí Quyết Từ Các Chuyên Gia",
    titleEn: "Shooting Technique: Expert Tips and Tricks",
    excerpt: "Những bí quyết giúp bạn cải thiện kỹ thuật shooting trong Pickleball.",
    excerptEn: "Tips to improve your shooting technique in Pickleball.",
    content: "Kỹ thuật shooting đòi hỏi sự kết hợp giữa sức mạnh và độ chính xác...",
    date: "2024-03-01",
    category: "Hướng dẫn",
    categoryEn: "Tutorial",
    image: "https://i.pinimg.com/736x/30/6d/44/306d441b00720a0479506c9bfe57e303.jpg",
    author: "HLV Nguyễn Hùng"
  },
  {
    id: 9,
    title: "Cần Thơ Charity Tournament: Kết Hợp Thể Thao Và Thiện Nguyện",
    titleEn: "Can Tho Charity Tournament: Combining Sports and Charity",
    excerpt: "Giải đấu đặc biệt nhằm gây quỹ cho trẻ em vùng khó khăn tại Đồng bằng Sông Cửu Long.",
    excerptEn: "Special tournament to raise funds for children in difficult circumstances in the Mekong Delta.",
    content: "Giải Pickleball Cần Thơ Charity không chỉ là sân chơi thể thao mà còn là cầu nối thiện nguyện...",
    date: "2024-02-28",
    category: "Sự kiện",
    categoryEn: "Events",
    image: "https://i.pinimg.com/736x/30/6d/44/306d441b00720a0479506c9bfe57e303.jpg",
    author: "Lê Thanh"
  },
  {
    id: 10,
    title: "10 Điều Cần Biết Trước Khi Tham Gia Giải Đấu Đầu Tiên",
    titleEn: "10 Things to Know Before Your First Tournament",
    excerpt: "Hướng dẫn chi tiết dành cho những người mới bắt đầu tham gia giải đấu Pickleball.",
    excerptEn: "Detailed guide for beginners entering their first Pickleball tournament.",
    content: "Tham gia giải đấu Pickleball lần đầu có thể khiến bạn cảm thấy hồi hộp...",
    date: "2024-02-25",
    category: "Hướng dẫn",
    categoryEn: "Tutorial",
    image: "https://i.pinimg.com/736x/30/6d/44/306d441b00720a0479506c9bfe57e303.jpg",
    author: "Đặng Minh"
  }
];

export const stats = {
  totalPlayers: 1250,
  totalTournaments: 48,
  provinces: 25,
  activeTournaments: 3
};
